### ISSUE TITLE
Tags being cleared

### ISSUE THREAD

**Issue by wgeraghty** [Ethiraric/yaml-rust2#10]
The tags list is being cleared between documents:

```
%YAML 1.1
%TAG !t! tag:test,2024:
--- !t!1 &1
foo: "bar"
--- !t!2 &2
baz: "qux"
```

Results in `ScanError { mark: Marker { index: 61, line: 5, col: 4 }, info: "the handle wasn't declared" }`.

Removing [`self.tags.clear()`](https://github.com/Ethiraric/yaml-rust2/blob/eaa4fc351de45f35a0826492683c58ead2a9060d/src/parser.rs#L598) seems to resolve it but I'm not sure if this is correct behavior or not.

**Comment by davvid** [comment]
It looks like test [QLJ7](https://github.com/yaml/yaml-test-suite/blob/ccfa74e56afb53da960847ff6e6976c0a0825709/src/QLJ7.yaml#L5) says that this is the expected behavior:

To make this work you'd have to write the yaml like so:

```yaml
%YAML 1.1
%TAG !t! tag:test,2024:
--- !t!1 &1
foo: "bar"
...
%TAG !t! tag:test,2024:
--- !t!2 &2
baz: "qux"
```

Rationale(?): each document is self-contained. I believe this can be resolved.

**Comment by davvid** [comment]
Are you seeing these in files in the wild @wgeraghty? If so, this might be another scenario where we might want an opt-in state flag on the Parser struct to keep tags across documents, even if it might be non-standard.

I can see that being generally useful, and avoiding the `self.tags.clear()` call with a boolean flag is a pretty small branch in the code that we'd have to take and won't impact overall performance.

I created PR #12 with a proof of concept on how we might support this.

**Comment by wgeraghty** [comment]
It's the format used in some of the files in a Unity `*.unitypackage` file.  Here's a snippet from an `asset` file:

```
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!29 &1
OcclusionCullingSettings:
  m_ObjectHideFlags: 0
  serializedVersion: 2
  m_OcclusionBakeSettings:
    smallestOccluder: 5
    smallestHole: 0.25
    backfaceThreshold: 100
  m_SceneGUID: 00000000000000000000000000000000
  m_OcclusionCullingData: {fileID: 0}
--- !u!4 &222201 stripped
Transform:
  m_PrefabParentObject: {fileID: 4128245942947034, guid: e1937d885ef6d394586883b9c80d463c,
    type: 2}
  m_PrefabInternal: {fileID: 222200}
```
