### ISSUE TITLE
Please consider a new release with updated dependencies

### ISSUE THREAD

**Issue by kinnison** [Ethiraric/yaml-rust2#33]
I use yaml-rust2 in a project where we're not ready to commit to something as potentially breaking as saphyr.  We'd like to eventually since we primarily just use the content which would be in saphyr-parser but for now we're kinda sticking to more stable crates.

Unfortunately we're very size-sensitive and complexity-of-dependency-tree sensitive and as a result we could do with a version of yaml-rust2 which has its hashlink dependency updated to 0.9.

I am prepared to organise a branch and testing to ensure the update is good; though given hashlink's API is part of yours, it probably implies that we would need to do a 0.9.0 release of yaml-rust2 rather than 0.8.2.

Is this something that this project would entertain, given that saphyr-parser does not appear to be presenting as production-ready yet?

**Comment by Ethiraric** [comment]
I can use the following set of dependencies without changing any piece of code:

```toml
[dependencies]
arraydeque = "0.5"
encoding_rs = { version = "^0.8", optional = true }
hashlink = "0.9"

[dev-dependencies]
libtest-mimic = "0.4"
quickcheck = "1.0"
```

I took the opportunity to remove the patch version requirement, which may help with binary size.
Only the transitive dependency `hashbrown` would not be updated. The rest would be `dev-dependencies`.

`libtest-mimic` has had a bunch of updates, but updating it fires a ton of errors that I don't want to spend time fixing.
I think it probably is a bit too early for a `0.9.0`? But I have no experience in evaluating that. I'm not fond of the idea of bumping the minor for just a dependency update.

Since I have not changed any code in the crate, I wonder if it's okay to just release a patch version?
It might break if someone is using a set `hashlink` dependency on their project alongside `yaml-rust2` though.
Something like:
```toml
hashlink = "0.8"
yaml-rust2 = "0.8.newversion"
```
```rs
let map = hashlink /*v0.8*/ ::new(something);
let yaml = yaml_rust2::Yaml::Hash(map /*expects 0.9*/);
```

I'm open to advice and suggestions (cc @davvid)
