### ISSUE TITLE
Can't iterate over hash

### ISSUE THREAD

**Issue by Ecco** [Ethiraric/yaml-rust2#39]
It's not possible to iterate over hash values.

Assuming the following YAML doc:
```yaml
fields:
  foo:
    value: 1
  bar:
    value: 2
```
Then this code fails (silently):
```rust
    assert_eq!(2, &doc["fields"].clone().into_iter().count()); // Value of 0 instead of 2
```
